### ISSUE TITLE
[PROFILE] Experiences and Trainings tables are foreigns keys linked with ID

### ISSUE THREAD

**Issue by FlorianVDP** [ecvdbdx/labo-union#59]
Experiences and Trainings tables are foreigns keys linked with ID, and we want to check if we delete user's profile this action also delete experiences and trainings linked.

**Comment by ValMgr** [comment]
Just select cascade on delete trainings and exp if profile is deleted (And profile is also deleted on cascade if users is removed)

<img width="449" alt="Capture d’écran 2023-05-02 à 10 30 05" src="https://user-images.githubusercontent.com/46904617/235617786-56c8571c-3332-45e9-b2a1-35304afb327b.png">
